# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  About: /about
  Friends: /Friends
  Feedback:
    url: https://support.qq.com/product/67072
    icon: commenting

# Title on top left of menu. Leave empty to use main blog title
menu_title: SanTu

# URL of the Home page image
#index_cover: /img/home-bg.jpeg
#index_cover: https://bing.ioliu.cn/v1/rand
index_cover: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture
archive_cover: /img/joey-kyber-GPxgi4J82E4-unsplash.jpg
#index_cover: /img/home-bg-color-sea.jpeg
#index_cover: /img/pexels-photo-2356087.jpeg

# Default post title
default_post_title: 无题

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Fill in your Baidu Tongji  tracking ID to enable Baidu Tongji.
baidu_tongji:
  enabled: true
  id: 227d0272c3ee3d56e68ea3d273217057

# Addthis ID
addthis:

# set your own favicon
favicon: /img/favicon.ico

# Social Accounts

github_url: https://github.com/masantu
mailto: imsantu.ma@gmail.com
film: /movies/
book: /books/
zhihu: https://www.zhihu.com/people/imoyao/
gitlab_url:
linkedin_url:
