# Custom nav
nav:
  title: "Rarpainting"
  subTitle: "Focus on Python"

favicon: "/img/favicon.ico"

# Custom background
background:
  color: "#eff0f6"
  image: "/img/natural_paper.png"
#  image: "https://www.toptal.com/designers/subtlepatterns/patterns/washi.png"
#  image: "https://www.toptal.com/designers/subtlepatterns/patterns/confectionary.png"

# Default post title
default_post_title: 无题

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Fill in your Baidu Tongji  tracking ID to enable Baidu Tongji.
baidu_tongji:
  enabled: true
  id: 227d0272c3ee3d56e68ea3d273217057

# Social media
social:
#  Dribbble: https://dribbble.com/clovertuan
#  Behance: https://www.behance.net/clovertuan
#  Lofter: http://clovertuan.lofter.com/
#  Instagram: https://www.instagram.com/clovertuan/
  HomePage: https://masantu.com/about/
  Zhihu: https://www.zhihu.com/people/imoyao
  Douban: https://www.douban.com/people/imoyao/
  Github: https://www.github.com/imoyao/

# Custom footer
mail: imsantu.ma@gmail.com
copyright: All rights reserved © 别院牧志

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project:
  #   path: /categories/Projects
  #   card: project-card
  # Stuffs:
  #   path: /tags/Stuffs
  #   card: article-card
  Home: /
  Tags: /tags
  Categories: /categories
  Archive: /archives
  About: /about

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  # category: Projects
  # tag: 算法
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css
post_default_cover: https://img.xjh.me/random_img.php?type=bg&ctype=nature&return=302

card_style:
  home: project-card
  archive: article-card
  tag: article-card
  category: article-card

# category page
category_generator:
  category_per_page: 5
  post_per_category: 5

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
